### ISSUE TITLE
Exponential backoff for executors incompatible with default & max executor_reregistration_timeout 

### ISSUE THREAD

**Issue by mkomitee** [douban/pymesos#115]
A maximum interval of 300 seconds in the exponential backoff we use when reconnecting to agents, all but ensures that an executor will not be able to reregister quickly enough once an agent comes back online.

Since the default executor_reregistration_timeout is 2secs (and mesos doesn't allow us to increase it beyond 15secs), we probably need the maximum interval to be 1 second for executor reconnect attempts.

**Comment by ariesdevil** [comment]
@mkomitee We will check it soon.

**Comment by ariesdevil** [comment]
https://github.com/douban/pymesos/pull/116
