### ISSUE TITLE
Add specific timeout for http requests

### ISSUE THREAD

**Issue by atringham** [douban/pymesos#119]
At the moment `_timeout` is being used as a timeout for http requests as well as a connect deadline.  This should be split into two separate timeouts.

A `http_timeout` for http connections and `_timeout` should remain for the necessary connect_deadline logic.

My approach would be to add an optional `http_timeout` in all the necessary `__init__` functions and add this whenever we are creating a `HTTPConnection`. I would default this to `DAY` to ensure the behaviour would not change by default.

Happy to provide a PR for this if you agree with the approach

**Comment by ariesdevil** [comment]
Agreed

**Comment by scrosby** [comment]
When do you think you'll release a new version with this fix?

**Comment by ariesdevil** [comment]
Done. https://github.com/douban/pymesos/releases/tag/0.3.12
