### ISSUE TITLE
pymesos doesn't install on python 3.7

### ISSUE THREAD

**Issue by diekhans** [douban/pymesos#122]
pymesos 0.3.12 does not install from pypi on python 3.7.  This is due to the http_parser package C code not being compatible with py3.7.   

http_parser appears to be no longer maintained, with the last pypi release in 2013.  Suggest dropping this package.

[pymesos-error.txt](https://github.com/douban/pymesos/files/4079092/pymesos-error.txt)

**Comment by diekhans** [comment]
I have created a ticket for http_parser: https://github.com/benoitc/http-parser/issues/90

**Comment by ariesdevil** [comment]
Temporary repair https://github.com/douban/pymesos/pull/123

**Comment by diekhans** [comment]
We already tried this, its does not allow pymesos to be installed from pypi, so it doesn't solve our problem.  Please reopen ticket

**Comment by ariesdevil** [comment]
Sorry for this. Once [this pr](https://github.com/benoitc/http-parser/pull/86#issuecomment-608375077) get merged, I'll update the install requirements and publish it ASAP.

**Comment by ariesdevil** [comment]
Done https://pypi.org/project/pymesos/0.3.15/
