### ISSUE TITLE
Should acknowledgement reply to slave directly or master?

### ISSUE THREAD

**Issue by BusyJay** [douban/pymesos#2]
I have no idea how old version mesos works, but seems in version 0.21, acknowledgements are sent to master and then forwarded to slave. When using pymesos with 0.21, tasks won't be moved to completed tasks because master doesn't get the acknowledgements. I take a look at the native implementation, it seems the official version goes to master despite of what pid is.

**Comment by windreamer** [comment]
https://github.com/apache/mesos/commit/90415006db79f127aa26a41f4bbc6d327f92c3dc induced this change. We are currently running 0.20.1 now, and this may be fixed later.

**Comment by windreamer** [comment]
fixed in 50cfca968a014ea5fef4eecf7238d5222baeec81, thx
