### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by wkf** [douban/pymesos#38]
Hey there, thanks for writing this library. I was wondering what the status is for python 3 support? I ran into some data encoding/decoding issues (that I was mostly able to work around) when I tried.

**Comment by windreamer** [comment]
It should be ok with Python 3, though some corner case may not be properly handled. If u can help up to improve Python 3 support, please PR here. U can also open an issue to describe the details, we will dig into it and fix it ASAP.

Thanks

**Comment by windreamer** [comment]
I think this is an duplication of https://github.com/douban/pymesos/issues/33, feel free to reopen
