### ISSUE TITLE
代码貌似有点问题

### ISSUE THREAD

**Issue by ballbillow** [douban/pymesos#4]
1：slave.py中
from mesos.interace.mesos_pb2 import *，这里interace应该是interface吧
2：原始的mesos中应该应该没有interface这个包吧

**Comment by windreamer** [comment]
确实是有问题，slave这部分本来是尝试实现一个python版的slave，但是由于对这个目标的需求不强烈了所以就中断了。这部分代码也没有充分测试过。感谢您对错误的指出，在 d023b75 中应该修复了这个错误

另外mesos.interface是 [mesos.interface](https://pypi.python.org/pypi/mesos.interface/0.20.0) 这个包

**Comment by ballbillow** [comment]
赞响应速度，呵呵
