### ISSUE TITLE
mismatch between pymesos API and mesos scheduler HTTP API spec

### ISSUE THREAD

**Issue by saitejar** [douban/pymesos#53]
1. killTask method of scheduler driver doesn't take agent_id as argument.
2. The body of killTask is incorrect, task_id should have another key "value"

`def killTask(self, task_id):
        framework_id = self.framework_id
        assert framework_id
        body = dict(
            type='KILL',
            framework_id=dict(
                value=framework_id,
            ),
            kill=dict(
                task_id=task_id,
            ),
        )
        self._send(body)
`
Scheduler HTTP api spec for Kill task:
KILL Request (JSON):
POST /api/v1/scheduler  HTTP/1.1
Host: masterhost:5050
Content-Type: application/json
Mesos-Stream-Id: 130ae4e3-6b13-4ef4-baa9-9f2e85c3e9af
{
  "framework_id"    : {"value" : "12220-3440-12532-2345"},
  "type"            : "KILL",
  "kill"            : {
    "task_id"   :  {"value" : "12220-3440-12532-my-task"},
    "agent_id"  :  {"value" : "12220-3440-12532-S1233"}
  }
}
KILL Response:
HTTP/1.1 202 Accepted

**Comment by windreamer** [comment]
Thanks for this issue!

1. For the `agent_id` argument, Pymesos implements the "official" Scheduler interface according to [this](https://github.com/apache/mesos/blob/master/src/python/interface/src/mesos/interface/__init__.py#L208). I am going to dig and discuss with the mesos guys to figure out.

2. This is definitely a bug, PR is on the way.

**Comment by windreamer** [comment]
OK, for 2.
currently, `task_id` should be like this: `{"value":"xxxxxxx"}`
This has a historical reason: the interface was a Protobuf struct, and now is an equivalent Dict.

**Comment by windreamer** [comment]
for `agent_id`:
it is optional according to [spec](https://github.com/apache/mesos/blob/master/include/mesos/v1/scheduler/scheduler.proto#L301)

**Comment by saitejar** [comment]
Thank you for taking up the issue. 
task_id as {"value":"xxxxxxx"} works, thank you.
