### ISSUE TITLE
No Subscribe/Register API end point in scheduler driver

### ISSUE THREAD

**Issue by saitejar** [douban/pymesos#54]
There is no subscribe API end point in the scheduler driver.
Though registration happens on driver.start() implicitly, in case we 
need to reregister due to disconnection from mesos master,
there is no API call for it currently.

**Comment by windreamer** [comment]
unfortunately, this is how mesos design & implement the interface.
Native C/Python drivers are all follow this way.

**Comment by saitejar** [comment]
Okay, I see, I think driver's start() method takes care of registration. Need to call it again to reregister. 
Thank you for the reply.
