### ISSUE TITLE
Heartbeat Callback for scheduler

### ISSUE THREAD

**Issue by saitejar** [douban/pymesos#61]
According to Scheduler HTTP API v1(link on pymesos [README](https://github.com/douban/pymesos)), there should be a heartbeat callback for the scheduler. 
It seems like the callback is suppressed in PyMesos and not exposed to pymesos clients, may be to be compliant with v0 API.

I was pointed to these messages in Mesos slack discussion by Anand Mazumdar when I asked about this issue(v0/v1)

> Anand Mazumdar [6:06 PM] 
> @saitejar The supported python bindings still use the old v0 API (driver based). You might want to look at `pymesos` instead that uses the new v1 Scheduler API.
> 
> This has come up in the past: https://mesos.slack.com/archives/C1KSH30JF/p1488943124000842
> Anand Mazumdar
> @windreamer : The official interface (v0) won’t ever support the v1 API, so you are free to pick a method name of your choice.
> Posted in #http-apiMarch 7th at 10:18 PM
> 
> [6:10]  
> Something that they might already be fixing. @windreamer maintains it and would know more about the plans.

Can we expect heartbeat callback to be supported anytime soon?

**Comment by windreamer** [comment]
May I know why you need the heartbeat callback? I thought it was just for connection keep-alive, and no need for end user exposed to this detail.

**Comment by saitejar** [comment]
I see, but the connection is not keeping alive in my case(Mesos master puts the framework in disconnected state). So, it is upon the framework to reconnect to the master. If it is done by pymesos, it would be great, otherwise the callback should be exposed to framework. I feel, heartbeat is necessary but not sufficient to keep alive.

**Comment by windreamer** [comment]
Connection should be kept alive transparently by pymesos. Can you give us some more information about this case?

**Comment by saitejar** [comment]
Sure, I got the following log from a disconnection. 

`WARNING:kazoo.client:Connection dropped: socket connection broken
 WARNING:kazoo.client:Transition to CONNECTING
 WARNING:kazoo.client:Session has expired
 WARNING:__main__:disconnected
ERROR:pymesos.process:Thread abort:
Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/pymesos/process.py", line 308, in _run
     if not conn.read():
   File "/usr/local/lib/python3.5/site-packages/pymesos/process.py", line 106, in read
     logger.warnig('Master is not available, retry.')
 AttributeError: 'Logger' object has no attribute 'warnig'
 WARNING:__main__:disconnected
 Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/websocket/_socket.py", line 80, in recv
   bytes_ = sock.recv(bufsize)
 socket.timeout: timed out`

Is the warnig typo causing any issue ?

**Comment by windreamer** [comment]
```
WARNING:kazoo.client:Connection dropped: socket connection broken
WARNING:kazoo.client:Transition to CONNECTING
WARNING:kazoo.client:Session has expired
WARNING:main:disconnected
```

It seems you failed to connect to the zookeeper cluster. Is the zookeeper addresses right? Have you tried to connect direct to the mesos master without zookeeper?

**Comment by windreamer** [comment]
And the typo have been fixed in the master branch.

**Comment by saitejar** [comment]
Zookeeper address is correct, and it does work fine for 20-30 min, before this issue occurs. Connecting directly with mesos master will probably work, but we would need to use zookeeper anyways for highly available mesos master. If not due to zookeeper, disconnection could happen due to network partition, but the framework should be able to reregister with the mesos master detecting such scenarios. I feel, heartbeat can help in such cases.

**Comment by windreamer** [comment]
`WARNING:kazoo.client:Connection dropped: socket connection broken`

According to the log, the zookeeper connection was broken at first, which led to master re-selectction and reconnect.

And the bug should be fixed in master, and if you using the master version, the reconnection should be successful.

**Comment by saitejar** [comment]
Can you please release the new master version as a new version, so that pip install works. 
(With just the typo fix, it still disconnects)

**Comment by windreamer** [comment]
cf #65

**Comment by windreamer** [comment]
0.2.12 released

**Comment by saitejar** [comment]
The fix did not seem solve the issue. It happens again. I have some mesos logs. 

`6acebb474b1-0000 (framework_ABC)
mesos_1     | I0411 00:07:46.511173    12 master.cpp:6517] Sending 1 offers to framework 0b582846-83e0-4a49-9e48-d6acebb474b1-0000 (framework_ABC)
mesos_1     | I0411 00:07:46.526757     6 master.cpp:1297] Framework 0b582846-83e0-4a49-9e48-d6acebb474b1-0000 (framework_ABC) disconnected
mesos_1     | I0411 00:07:46.526831     6 master.cpp:2902] Disconnecting framework 0b582846-83e0-4a49-9e48-d6acebb474b1-0000 (framework_ABC)
mesos_1     | I0411 00:07:46.526860     6 master.cpp:2926] Deactivating framework 0b582846-83e0-4a49-9e48-d6acebb474b1-0000 (framework_ABC)
mesos_1     | W0411 00:07:46.527034     6 master.hpp:2266] Master attempted to send message to disconnected framework 0b582846-83e0-4a49-9e48-d6acebb474b1-0000 (framework_ABC)
mesos_1     | I0411 00:07:46.527235    11 hierarchical.cpp:386] Deactivated framework 0b582846-83e0-4a49-9e48-d6acebb474b1-0000
mesos_1     | W0411 00:07:46.527693     6 master.hpp:2272] Unable to send event to framework 0b582846-83e0-4a49-9e48-d6acebb474b1-0000 (framework_ABC): connection closed
mesos_1     | I0411 00:07:46.528533     6 master.cpp:1310] Giving framework 0b582846-83e0-4a49-9e48-d6acebb474b1-0000 (framework_ABC) 1weeks to failover
mesos_1     | 2017-04-11 00:08:27,140:1(0x7feb8329c700):ZOO_WARN@zookeeper_interest@1570: Exceeded deadline by 53ms`

**Comment by windreamer** [comment]
These are logs from mesos. What about logs of the framework?

**Comment by saitejar** [comment]
Sorry, I could not get back earlier. 
Framework has no unusual logs. 
`mlengine_1  | INFO:__main__:resourceOffers offers=[{'executor_ids': [{'value': 'Executor'}], 'url': {'path': '/slave(1)', 'address': {'hostname': '10.1.1.200', 'port': 5051, 'ip': '10.1.1.200'}, .....,{'executor_ids': [{'value': 'Executor'}], 'url': {'path': '/slave(1)', 'address': {'hostname': '10.1.1.201' ...... 'ranges': {'range': [{'end': 32000, 'begin': 31000}]}, 'role': '*'}]}]

mlengine_1  | INFO:__main__:Declined offer 792d236e-1d4a-493f-aba2-92ecd6b20b16-O8

mlengine_1  | INFO:__main__:Declined offer 792d236e-1d4a-493f-aba2-92ecd6b20b16-O9`


Corresponding Mesos Log:

`mesos_1     | I0419 18:10:40.155709     6 master.cpp:6517] Sending 2 offers to framework cad12a2d-9dbd-4330-b856-7ed233ac0c05-0000 (ABC)  
mesos_1     | I0419 18:10:40.164337    12 http.cpp:391] HTTP POST for /master/api/v1/scheduler from 172.18.0.1:53796 . 
mesos_1     | I0419 18:10:40.165478    12 master.cpp:4505] Processing DECLINE call for offers: [ cad12a2d-9dbd-4330-b856-7ed233ac0c05-O222 ] for framework cad12a2d-9dbd-4330-b856-7ed233ac0c05-0000 (ABC) . 
mesos_1     | I0419 18:10:40.171816    12 http.cpp:391] HTTP POST for /master/api/v1/scheduler from 172.18.0.1:53796 . 
mesos_1     | I0419 18:10:40.172338    12 master.cpp:4505] Processing DECLINE call for offers: [ cad12a2d-9dbd-4330-b856-7ed233ac0c05-O223 ] for framework cad12a2d-9dbd-4330-b856-7ed233ac0c05-0000 (ABC) . 
mesos_1     | I0419 18:10:41.407927     7 http.cpp:391] HTTP GET for /master/state from 172.18.0.1:53840 with User-Agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36' . 
mesos_1     | I0419 18:10:45.138394     8 master.cpp:1297] Framework cad12a2d-9dbd-4330-b856-7ed233ac0c05-0000 (ABC) disconnected . 
mesos_1     | I0419 18:10:45.139780     8 master.cpp:2902] Disconnecting framework cad12a2d-9dbd-4330-b856-7ed233ac0c05-0000 (ABC) . 
mesos_1     | I0419 18:10:45.139955     8 master.cpp:2926] Deactivating framework cad12a2d-9dbd-4330-b856-7ed233ac0c05-0000 (ABC) . 
mesos_1     | I0419 18:10:45.140123     8 master.cpp:1310] Giving framework cad12a2d-9dbd-4330-b856-7ed233ac0c05-0000 (ABC) 1weeks to failover` . 

This is the framework log after the disconnection(last lines in the log).
