### ISSUE TITLE
framework receives less than master offers

### ISSUE THREAD

**Issue by DrRibosome** [douban/pymesos#64]
Im not entirely sure if this is related to pymesos, but im seeing a case where if i schedule lots of jobs that only need 0.2 cpu (.1 for task, .1 for executor) on a 2 core agent, the resources offers supplied to the framework gradually contain fewer and fewer cpus until the jobs cannot be scheduled.

(As a note: Im running mesos on debian, and launching jobs inside docker containers)

For example, here is the first offer i receive (with hostname misc removed):
```
'framework_id': {'value': 'e06e2242-4f76-450d-9153-4616dc03e913-0044'}, 'allocation_info': {'role': '*'}, 'id': {'value':
 'e06e2242-4f76-450d-9153-4616dc03e913-O185'}, 'resources': [{'role': '*', 'type': 'SCALAR', 'name': 'cpus', 'scalar': {'value': 2.0}, 'allocation_info': {'role': '*'}}, {'role': '*', 'type': 'SCALAR', 'name': 'mem', 'scalar': {'value': 12031.0}, 'allocation_info': {
'role': '*'}}, {'role': '*', 'type': 'SCALAR', 'name': 'disk', 'scalar': {'value': 24987.0}, 'allocation_info': {'role': '*'}}, {'role': '*', 'type': 'RANGES', 'name': 'ports', 'ranges': {'range': [{'begin': 31000, 'end': 32000}]}, 'allocation_info': {'role': '*'}}],
 'agent_id': {'value': 'e06e2242-4f76-450d-9153-4616dc03e913-S0'},
```

and then, after scheduling jobs eventually my final resource off looks like:
```
'framework_id': {'value': 'e06e2242-4f76-450d-9153-4616dc03e913-0044'}, 'allocation_info': {'role': '*'}, 'id': {'value':
 'e06e2242-4f76-450d-9153-4616dc03e913-O192'}, 'resources': [{'role': '*', 'type': 'SCALAR', 'name': 'cpus', 'scalar': {'value': 0.1}, 'allocation_info': {'role': '*'}}, {'role': '*', 'type': 'SCALAR', 'name': 'mem', 'scalar': {'value': 32.0}, 'allocation_info': {'ro
le': '*'}}, {'role': '*', 'type': 'SCALAR', 'name': 'disk', 'scalar': {'value': 32.0}, 'allocation_info': {'role': '*'}}], 'agent_id': {'value': 'e06e2242-4f76-450d-9153-4616dc03e913-S0'},
```

At this point, I checked the mesos master, which reports 2 cpus offered, and there is nothing else running. Notably, mem/disk offer also seems to decrease. Is it possible that pymesos may not be relinquishing resources?

**Comment by windreamer** [comment]
Hmm，did your script actrually launch tasks with the offered resources？
If no tasks found in your framework UI，you may check `Offers` tab. All the offered resources should be displayed there.

`PyMesos` just a bridge for mesos and framework，and should not modify the allocation behaviour of mesos.

**Comment by DrRibosome** [comment]
got it - i can see jobs launching, and completing, but it seems like the resources requested are never released for some reason

**Comment by DrRibosome** [comment]
ok, looking closer, in the mesos web ui the tasks show up as completed, but the offer still containers the executor ids for past (completed) tasks. It seems to continue to count their resource usage as well. Is there something I should specifically do to terminate the executor and have mesos collect it?

**Comment by DrRibosome** [comment]
it looks like i needed to make sure to call `driver.abort()` to actually stop the driver - doing this fixes the problem

**Comment by windreamer** [comment]
Thanks for your share. Typically we just re-use the existing executor when possible, and the executor is running till framework ends. If you actually need short-lived executors, you may write a custom executor and let it exit when the task is finished. and you may receive a `executorLost` message to notify you the premature exit of the executor.
