### ISSUE TITLE
HA Scheduler, through persisting fwk id, seems not to work properly.

### ISSUE THREAD

**Issue by LuisMoralesAlonso** [douban/pymesos#71]
Doing an example scheduler a bit more complicated. I've added HA for the scheduler through persisting ID in redis.

When trying to subscribe the second time I receive the next message:

RuntimeError: Failed with HTTP 400: Failed to convert JSON into Call protobuf: Not expecting a JSON string for field 'framework_id'

The reason, I wonder, is due to including in the SUBSCRIBE call:

      if 'id' in self._framework:
            request['framework_id'] = self._framework['id']

The id is already in the framework_info dict, and it's not until you receive the response from master when you receive:

{
 "type"         : "SUBSCRIBED",
 "subscribed"   : {
     "framework_id"               : {"value":"12220-3440-12532-2345"},
     "heartbeat_interval_seconds" : 15
  }
}

**Comment by windreamer** [comment]
@LuisMoralesAlonso can I know how do you do the HA? And framework_id should be a `dict` instead of a `string`.

**Comment by LuisMoralesAlonso** [comment]
When I instantiate the MesosSchedulerDriver I check if the id already persisted in redis, if it's the case I include it in the framework dictionary:

    if connection.hexists(os.getenv('MARATHON_APP_ID'),'fwk_id'):
        logging.info("framework id already registered in redis")
        framework.id = connection.hget(os.getenv('MARATHON_APP_ID'),'fwk_id')

**Comment by windreamer** [comment]
@LuisMoralesAlonso `framework.id` should be something like `{"value":"12220-3440-12532-2345"}` instead of `"12220-3440-12532-2345"`

From the snippet above, `connection.hget(os.getenv('MARATHON_APP_ID'),'fwk_id')` always get a string? so maybe you need to do something like `framework.id = dict(value=connection.hget(os.getenv('MARATHON_APP_ID'),'fwk_id'))
` ?

**Comment by LuisMoralesAlonso** [comment]
It works!!!! Thnks!!!
