### ISSUE TITLE
Socket errors are not handled properly which is resulting in unexpected behavior

### ISSUE THREAD

**Issue by sagar8192** [douban/pymesos#79]
We are using pymesos in https://github.com/Yelp/task_processing. I ran into an issue where we accepted an offer and launched a task. The elected master was having some issues with networking. Pymesos sent an HTTP request but timed out while getting a response back from master. Master never received the task, thus it did not launch it. socket.timeout error was raised, caught and ignored by pymesos. Our framework assumed that the task has been launched because pymesos did not throw any error. But, it was not actually launched.

Stack trace from our application:
https://gist.github.com/sagar8192/da8f39e04366372815583677dd48c9c5

For POST requests, pymesos should not swallow timeout exceptions. It should raise an exception or return False so that applications know that their request failed.

**Comment by windreamer** [comment]
Hi @sagar8192 ,

I think you can get the exception when you do `try... except...` around `File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/task_processing/plugins/mesos/execution_framework.py", line 515, in resourceOffers`

Please note，we do re-throw the timeout exception, ref: https://github.com/douban/pymesos/blob/master/pymesos/scheduler.py#L162 . And from the traceback you post, it can be verified too.

**Comment by sagar8192** [comment]
Hi @windreamer,
                            Thanks for getting back quickly. You are right. Let me add try except and deal with it.
