### ISSUE TITLE
how do i get status of a task from scheduler?

### ISSUE THREAD

**Issue by eugenepark1** [douban/pymesos#81]

**Comment by windreamer** [comment]
Hi @eugenepark1 ,
   Typically you need to track the status change of a task in your scheduler. And you can get the current status of the task when you do `reconcile` in your scheduler.

**Comment by eugenepark1** [comment]
class CQScheduler(Scheduler):
    def __init__(self, executor):
        self.executor = executor

    def resourceOffers(self, driver, offers):
        '''
        this resource offer process repeats when tasks finish and new resources become free
        @todo: 
            - 
        @fixed
            - should Scheduler dispatch more than one jobs per call
            
        '''
        # this is where Bedrock will dispatch jobs
        filters = {'refuse_seconds': 0.01}

        offers_to_decline = []
        tasks = []
        offers_to_accept = []
        declineRest = False

        for offer in offers:
            
            if declineRest:
                offers_to_decline.append(offer.id)
                continue

            cpus = self.getResource(offer.resources, 'cpus')
            mem = self.getResource(offer.resources, 'mem')

            tasks = binpack_tasks(cpus, mem, offer, self.executor)

            if len(tasks) > 0:
                offers_to_accept.append(offer.id)
            else:
                offers_to_decline.append(offer.id)
            
            # one offer at a time
            declineRest = True

        if len(offers_to_decline) > 0:
            driver.declineOffer(offers_to_decline, filters)
            
        if len(offers_to_accept) > 0:
            driver.launchTasks(offers_to_accept, tasks, filters)

    def getResource(self, res, name):
        for r in res:
            if r.name == name:
                return r.scalar.value
        return 0.0

    def statusUpdate(self, driver, update):
        logging.debug('Status update TID %s %s',
                      update.task_id.value,
                      update.state)
def main():
    executor = Dict()
    executor.executor_id.value = 'CQExecutor'
    executor.name = executor.executor_id.value
    executor.command.value = '%s %s' % (
        sys.executable,
        abspath(join(dirname(__file__), 'br_dispatch_executor.py'))
    )
    executor.resources = [
        dict(name='mem', type='SCALAR', scalar={'value': EXECUTOR_MEM}),
        dict(name='cpus', type='SCALAR', scalar={'value': EXECUTOR_CPUS}),
    ]

    framework = Dict()
    framework.user = getpass.getuser()
    framework.name = "CQFramework-%s,%s" % (HOST, PID)
    framework.hostname = socket.gethostname()

    driver = MesosSchedulerDriver(
        CQScheduler(executor),
        framework,
        master,
        use_addict=True,
    )

    driver_thread = Thread(target=run_driver_thread, args=())
    driver_thread.daemon = True
    driver_thread.start()


So, how would i call reconcile from the above code? I assume its not from driver but rather the CQScheduler itself??

**Comment by windreamer** [comment]
@eugenepark1 when task is finished， `statusUpdate` will be called， and you need to bookkeep  the statuses of all the tasks, then you can know when all the jobs are finished.

**Comment by eugenepark1** [comment]
thank you. using statusUpdate does help me keep track of jobs.
