### ISSUE TITLE
Custom field on update dictionary not working

### ISSUE THREAD

**Issue by eugenepark1** [douban/pymesos#82]
for example in the below, if i add a new key to update dictionary i.e. update.new_key = 1

    class MinimalExecutor(Executor):
        def launchTask(self, driver, task):
           def run_task(task):
              update = Dict()
              update.task_id.value = task.task_id.value
              update.state = 'TASK_RUNNING'
              update.timestamp = time.time()
              update.new_key = 1
              driver.sendStatusUpdate(update)

              print(decode_data(task.data), file=sys.stderr)
              time.sleep(30)

              update = Dict()
              update.task_id.value = task.task_id.value
              update.state = 'TASK_FINISHED'
              update.timestamp = time.time()
              update.new_key = 1
              driver.sendStatusUpdate(update)
    thread = Thread(target=run_task, args=(task,))
    thread.start()
   

and in scheduler.py 

    def statusUpdate(self, driver, update):
      logging.debug('Status update TID %s %s %s',
                      update.task_id.value,
                      update.state,
                       update.new_key)

update.new_key is shown an empty dictionary, {}, instead of 1 in the log

how do i add a new key to update dictionary destined for statusUpdate()?

**Comment by windreamer** [comment]
Unfortunately， you can not add new key in `update` message.
The `update` message is defined by Mesos http://mesos.apache.org/documentation/latest/scheduler-http-api/ , and can not be customized by the user.

https://github.com/douban/pymesos/blob/master/pymesos/subprocess/scheduler.py#L19 is an example you can refer to, and demonstrates how to book-keep the information of each task.

**Comment by eugenepark1** [comment]
Thank you - using update.data to send back a custom dict back to scheduler works
