### ISSUE TITLE
Framework does not get HeartBeats

### ISSUE THREAD

**Issue by premal** [douban/pymesos#93]
Hi @windreamer,
In this commit, https://github.com/douban/pymesos/commit/04501d10f8568065f626ec3fe8689d4f8fdbf9ee#diff-ab924b88fb1411cfeab6024b822161a8R95 , a change was made to suppress the Heart Beats events to the framework. Was there a reason behind it?

**Comment by windreamer** [comment]
Hi @premal ,
According to http://mesos.apache.org/documentation/latest/scheduler-http-api/#heartbeat , only the scheduler not the user needs to be aware of the heart beat. So we just receive and ignore it. And of course, we should monitor the heart beat interval to avoid network partition, but we have not implement this.
